dev: Ignore for mypy's sake some superclass calls
types-docutils isn't sufficient with recent (?) mypy versions, causing:

    nextstrain/cli/rst/sphinx.py:71: error: "dispatch_visit" undefined in superclass
    nextstrain/cli/rst/sphinx.py:88: error: "dispatch_departure" undefined in superclass

which seems to be because the docutils-stubs/nodes.pyi file installed by
types-docutils contains

    def __getattr__(…) -> Any

for nodes.NodeVisitor, which is apparently not understood by mypy.

Typeshed knows it's docutils stubs aren't great.¹  The docutils-stubs
distribution has a docutils-stubs/nodes.pyi² that mypy understands, but
installing that then breaks pyright.  Oy vey.

¹ https://github.com/python/typeshed/issues/1269

² Yes, both the docutils-stubs and types-docutils distributions install
  a "docutils-stubs" directory in Python's site-packages.  This is how
  typestubs are supposed to be installed for the package "docutils".