dev: Fix syntax of flake8 config file
The trailing comments were apparently bogus this whole time!  The
configuration documentation does mention this¹, though not sure it did
at the time I wrote the config initially.  In any case: oops.

flake8 version 6.0.0, released earlier today, started validating the
config and thus detecting the erroneous entries, which made our CI start
to fail with:

    ValueError: Error code '#' supplied to 'extend-ignore' option does
    not match '^[A-Z]{1,3}[0-9]{0,3}$'

Failures were limited to Python ≥3.8, as flake8 6.0.0 bumped its minimum
Python dep, so older Python versions kept using older flake8 versions,
but the syntax error affected them nevertheless.

¹ https://flake8.pycqa.org/en/latest/user/configuration.html